"""
Django settings for oneshop project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--nc49el@=)_ju0_6-w01#gj7t6)ur8ubbn4sexny9b=_34!skg"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "shop.apps.ShopConfig",
]

REST_FRAMEWORK = { 
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',  
        'rest_framework.renderers.JSONRenderer',
    )
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "oneshop.urls"
#
# TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates') #!!!!!!!!!!

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "oneshop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
MEDIA_ROOT = BASE_DIR/'media' #1 0/02/23 это путь к серверу для хранения файлов на компьютере.
MADEIA_URL = 'media'          # 10/02/23 это URL-адрес ссылки для браузера для доступа к файлам через Http
                           #BASE_DIR относительный путь корня в проэкте ' '
STATIC_ROOT = os.path.join(BASE_DIR, STATIC_URL) #это тоже мы
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

OUR_DOMAIN = 'http://127.0.0.1:8000'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STRIP_PUBLIC_KEY = 'pk_test_51MZptzGjQH43ny4DlKTUvQkJZcapvKpwC70wLLHhAqIzPIaL7fntFEKbtrVVLc964xpAeI9s4PuAbBH9A4SByvVW00wp58QxkU' # os.getenv('STRIPE_SECRET_KEY')

STRIP_SECRET_KEY = "sk_test_51MZptzGjQH43ny4DOHloi7ZtcDmItonkIKlSA64M4nBtGoW6ifbbwDoGk8tXoh0Xm9wZ6XZGNn2XGoGKQ58CgJPx00aDd8H4pZ"
