# Generated by Django 4.1 on 2023-02-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Название товара", max_length=50)),
                (
                    "description",
                    models.CharField(
                        help_text="Описпние товара до 200 символов", max_length=200
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="цена", max_digits=4
                    ),
                ),
            ],
            options={
                "ordering": ["name", "price"],
            },
        ),
    ]
