# Generated by Django 4.1 on 2023-02-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="product",
            new_name="item",
        ),
    ]
